### ISSUE TITLE
Add tilt effect with full page listening

### ISSUE THREAD

**Issue by Grienauer** [JB1905/universal-tilt.js#62]
with the original js libraries, it is possible to add "data-tilt-full-page-listening", then the tilt effect is used always and not only if someone is over the tilted object.
Is this feature on the roadmap or ist it in the actual implementation not possible to add?
thx!
I really like the gyro effect btw!

**Comment by JB1905** [comment]
Hi! This option is available and is called `base`. You should add `data-base="window"` to 
tilt element. In the next version this option will be updated to control the tilt based on another element e.g. div, section etc. not only window and tilt element. In other words: `full-page-listening` and `mouse-event-element` from original library will be combined into one option.

**Comment by Grienauer** [comment]
wow, this was fast. I just discovered it and wanted to write here, that everything is fine and I just not read the docs. thx!

**Comment by premitheme** [comment]
Hi, I like your library a lot. Just wondering if the "base" option enhancement (to accept any other element) will be implemented any soon.

Again thanks for your great work and effort.

Regards,
Ahmed

**Comment by JB1905** [comment]
@premitheme I'm still working on it. Thanks!
